import type { Translation } from '../types'

export default {
  brand: 'Starry Love Diary',
  nav: { story: 'Pour toi', spaces: 'Cinq espaces', privacy: 'Ton espace', menu: 'Ouvrir le menu', label: 'Navigation principale', skip: 'Aller au contenu', language: 'Choisir la langue' },
  hero: { title: 'Aime quelqu’un\nsans t’oublier toi-même.', body: 'Garde les petits frissons et accueille les émotions difficiles à nommer.\nEntre amour secret, signes ambigus et sentiments qui prennent toute la place,\napprends aussi à te retrouver.', explore: 'Découvre notre univers, à ton rythme' },
  comingSoon: 'Bientôt disponible',
  story: { title: 'Pour toi, qui penses à quelqu’un', paragraphs: ['Aimer quelqu’un peut être si doux.\nEt parfois, si fatigant.', 'Attendre un message, chercher le sens d’une phrase.\nUn regard qui illumine toute la journée,\npuis un silence qui fait tourner les pensées en boucle.', 'Starry Love Diary n’est pas là pour te dire d’arrêter d’aimer.', 'Juste pour garder une trace de ces petits frissons\net t’aider à démêler tes sentiments quand tu en as besoin.'], closing: 'Garde une place pour cette personne. Et pour toi aussi.' },
  spaces: { title: 'Cinq espaces pour ton histoire d’amour', items: [
    { title: 'Aujourd’hui', body: 'Tes émotions du jour, tes photos et tes petits élans du cœur. Tout commence ici.' },
    { title: 'Clarté', body: 'Quand tu penses sans cesse à cette personne, que tu attends son message ou que tes sentiments prennent trop de place, distingue les faits, les interprétations et ce que tu ignores encore. Reviens doucement à toi.' },
    { title: 'Empreintes', body: 'Garde ton journal, tes photos et les émotions du chemin. Un jour, en regardant derrière toi, tu verras tout le chemin parcouru.' },
    { title: 'Bocal d’étoiles', body: 'Recueille les émotions et les instants de clarté que tu souhaites garder, une petite étoile à la fois.' },
    { title: 'Nous', body: 'Note les dates importantes, les moments partagés, ses goûts, ses petites habitudes et tous ces détails dont tu te souviens.' },
  ] },
  clarity: { title: 'Quand les sentiments prennent un peu trop de place…', statement: 'Garde les papillons. Laisse tes pensées souffler.', situations: ['Je pense tout le temps à cette personne.', 'J’attends son message.', 'J’ai l’impression de trop m’attacher.', 'Je ne sais plus si cette personne me plaît.', 'Je ne sais pas si nous allons bien ensemble.'], body: 'Tu n’as pas besoin de toutes les réponses maintenant.\n\nSépare doucement les faits, ce que tu imagines, tes émotions et tes besoins. Peut-être verras-tu un peu mieux ce qui te ferait du bien, ici et maintenant.', words: ['Les faits', 'Les interprétations', 'L’inconnu', 'Toi'] },
  daily: { title: 'Une petite étoile de mots, rien que pour aujourd’hui', statement: 'Certains mots aimeraient te rencontrer aujourd’hui.', body: 'Chaque jour, ouvre Starry Love Diary et découvre une pensée sur l’amour, juste pour ce moment.\n\nRien à rattraper, pas même hier.\nLes mots que tu rencontres aujourd’hui sont un petit rendez-vous qui n’appartient qu’à ce jour.' },
  cat: { title: 'Quand tu ne sais pas à qui te confier, commence par le chat noir.', body: 'Il ne te presse pas d’oublier quelqu’un.\nIl ne décide pas non plus qui tu devrais aimer.\n\nIl reste simplement près de toi, en silence,\npendant que tu apprends à comprendre ton cœur.', alt: 'Un chat noir contemple tranquillement une étoile' },
  privacy: { title: 'Tes sentiments ont leur jardin secret', body: 'L’amour peut être très intime.\nUn journal devrait l’être aussi.\n\nStarry Love Diary tient à ton espace personnel. Nous souhaitons t’offrir un endroit où tu te sens à l’aise pour garder tes émotions et tes souvenirs.' },
  final: { body: 'Écris ce qui fait battre ton cœur.\nRetrouve-toi, petit à petit.' },
  legal: { privacy: 'Politique de confidentialité', terms: 'Conditions d’utilisation', back: 'Retour à l’accueil', pending: 'Le contenu complet sera disponible avant le lancement de l’application.', privacyNotice: 'La Politique de confidentialité officielle sera publiée avant le lancement de l’application.', termsNotice: 'Les Conditions d’utilisation officielles seront publiées avant le lancement de l’application.', privacySections: ['Stockage des données', 'Photos', 'Fonctions de partage', 'Services tiers', 'Contact', 'Date de mise à jour'], termsSections: ['Champ d’utilisation', 'Contenu des utilisateurs', 'Limites des fonctionnalités', 'Clause de non-responsabilité', 'Propriété intellectuelle', 'Mise à jour des conditions', 'Contact'] },
} satisfies Translation
